version: "3.9"

services:
  web:
    build: .
    container_name: resume_api
    command: python run.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5001:5001"
    depends_on:
      - redis
    volumes:
      - .:/app

  celery:
    build: .
    container_name: resume_worker
    command: celery -A celery_worker.celery worker --loglevel=info --pool=solo
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:6.2
    container_name: redis_resume
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "6379:6379"